/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: low_battery-24-1
* Dimensions:  24 * 24
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorslow_battery-24-1[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Pallow_battery-24-1 = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorslow_battery-24-1[0]
};

static GUI_CONST_STORAGE unsigned char aclow_battery-24-1[] = {
  /* RLE: 146 Pixels @ 000,000*/ 146, 0x01, 
  /* RLE: 019 Pixels @ 002,006*/ 19, 0x00, 
  /* RLE: 005 Pixels @ 021,006*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 002,007*/ 1, 0x00, 
  /* RLE: 017 Pixels @ 003,007*/ 17, 0x01, 
  /* RLE: 001 Pixels @ 020,007*/ 1, 0x00, 
  /* RLE: 005 Pixels @ 021,007*/ 5, 0x01, 
  /* RLE: 001 Pixels @ 002,008*/ 1, 0x00, 
  /* RLE: 017 Pixels @ 003,008*/ 17, 0x01, 
  /* ABS: 002 Pixels @ 020,008*/ 0, 2, 0x00, 
  /* RLE: 004 Pixels @ 022,008*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 002,009*/ 1, 0x00, 
  /* RLE: 018 Pixels @ 003,009*/ 18, 0x01, 
  /* RLE: 001 Pixels @ 021,009*/ 1, 0x00, 
  /* RLE: 004 Pixels @ 022,009*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 002,010*/ 1, 0x00, 
  /* RLE: 018 Pixels @ 003,010*/ 18, 0x01, 
  /* ABS: 006 Pixels @ 021,010*/ 0, 6, 0x00, 0x11, 0x10, 
  /* RLE: 018 Pixels @ 003,011*/ 18, 0x01, 
  /* ABS: 006 Pixels @ 021,011*/ 0, 6, 0x00, 0x11, 0x10, 
  /* RLE: 018 Pixels @ 003,012*/ 18, 0x01, 
  /* ABS: 006 Pixels @ 021,012*/ 0, 6, 0x00, 0x11, 0x10, 
  /* RLE: 018 Pixels @ 003,013*/ 18, 0x01, 
  /* ABS: 006 Pixels @ 021,013*/ 0, 6, 0x00, 0x11, 0x10, 
  /* RLE: 018 Pixels @ 003,014*/ 18, 0x01, 
  /* RLE: 001 Pixels @ 021,014*/ 1, 0x00, 
  /* RLE: 004 Pixels @ 022,014*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 002,015*/ 1, 0x00, 
  /* RLE: 017 Pixels @ 003,015*/ 17, 0x01, 
  /* ABS: 002 Pixels @ 020,015*/ 0, 2, 0x00, 
  /* RLE: 004 Pixels @ 022,015*/ 4, 0x01, 
  /* RLE: 001 Pixels @ 002,016*/ 1, 0x00, 
  /* RLE: 017 Pixels @ 003,016*/ 17, 0x01, 
  /* RLE: 001 Pixels @ 020,016*/ 1, 0x00, 
  /* RLE: 005 Pixels @ 021,016*/ 5, 0x01, 
  /* RLE: 019 Pixels @ 002,017*/ 19, 0x00, 
  /* RLE: 147 Pixels @ 021,017*/ 147, 0x01, 


  0};  /* 88 for 576 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmlow_battery-24-1 = {
  24, /* XSize */
  24, /* YSize */
  12, /* BytesPerLine */
  GUI_COMPRESS_RLE4, /* BitsPerPixel */
  aclow_battery-24-1,  /* Pointer to picture data (indices) */
  &Pallow_battery-24-1  /* Pointer to palette */
 ,GUI_DRAW_RLE4
};

/* *** End of file *** */
